apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-mongodb
  template:
    metadata:
      labels:
        app: authentication-mongodb
    spec:
      containers:
      - name: authentication-mongodb
        image: mongo
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        ports:
        - containerPort: 27017
