apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-depl
spec:
  selector:
    matchLabels:
      app: management-depl
  template:
    metadata:
      labels:
        app: management-depl
    spec:
      containers:
      - name: management-depl
        image: pharmacy-management-service
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"