apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-postgresdb
spec:
  selector:
    matchLabels:
      app: pharmacy-postgresdb
  template:
    metadata:
      labels:
        app: pharmacy-postgresdb
    spec:
      containers:
      - name: pharmacy-postgresdb
        image: postgres
        resources:
          limits:
            cpu: "0.1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD 
          value: "postgres*8"
